catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url




urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),


    url(r'^maincatalog/(?P<pk>\d+)$', views.MainCatalogDetail.as_view(), name='main_catalog_detail'),



    url(r'^catalog/$', views.Catalog.as_view(), name='catalog'),
    url(r'^catalog/(?P<pk>\d+)$', views.CatalogDetail.as_view(), name='catalog_detail'),

    url(r'^goods/(?P<pk>\d+)$', views.GoodDetail.as_view(), name='good_detail'),



    # url(r'^goods/$', views.GoodListView.as_view(), name='goods'),
    # url(r'^goods/(?P<pk>\d+)$', views.GoodDetailView.as_view(), name='good-detail'),

    # url(r'^category/$', views.CatListView.as_view(), name='category'),
    # url(r'^category/(?P<pk>\d+)$', views.CatDetailView.as_view(), name='category-detail'),

    # url(r'^order/$', views.OrderListView.as_view(), name='order'),
    # url(r'^order/(?P<pk>\d+)$', views.OrderDetailView.as_view(), name='order-detail'),

    # url(r'^cat/$', views.CListView.as_view(), name='cat'),
    # url(r'^cat/(?P<pk>\d+)$', views.GDetailView.as_view(), name='detail'),

    # url(r'^cat/$', views.CatsListView.as_view(), name='categorys'),
]

shopz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# from . import views, settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [

    
    path('admin/', admin.site.urls),      
    path('catalog/', include('catalog.urls')),    

    

    
    ]


urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse


class People(models.Model):
    name = models.CharField(max_length=200)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('people-detail', args=[str(self.id)])








class Category(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog_detail', args=[str(self.id)])




class Maincategory(models.Model):
    name = models.CharField(max_length=200)
    category = models.ManyToManyField(Category)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main_catalog_detail', args=[str(self.id)])





class Good(models.Model):
    name = models.CharField(max_length=200)
    decs = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="image")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('good_detail', args=[str(self.id)])




class Order(models.Model):
    name = models.CharField(max_length=200)
    good = models.ManyToManyField(Good)
    people = models.ForeignKey(People, on_delete=models.SET_NULL, null=True)
    
            

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('order-detail', args=[str(self.id)])

catalog/views.py
from django.shortcuts import render
from .models import Good, Maincategory, Category, People, Order
from django.views.generic import ListView, DetailView



#~~~~~~~~~~~~~~~~~  MAIN - КАТАЛОГ  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class MainCatalogDetail(DetailView):
    model = Maincategory
    template_name = "base_main_catalog_detail.html"


    @staticmethod
    def all_goods():
        return Good.objects.all()

   
    @staticmethod
    def all_category():
        return Category.objects.all()


    @staticmethod
    def all_maincat():
        return Maincategory.objects.all()



#~~~~~~~~~~~~~~~~~  КАТАЛОГ  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

class Catalog(ListView):
    model = Good
    template_name = "base_catalog.html"

    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_maincat():
        return Maincategory.objects.all()


    @staticmethod
    def all_category():
        return Category.objects.all()



#~~~~~~~~~~~~~~~~~  SUB КАТАЛОГ  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



class CatalogDetail(DetailView):
    model = Category
    template_name = "base_catalog_detail.html"

    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_maincat():
        return Maincategory.objects.all()


    @staticmethod
    def all_category():
        return Category.objects.all()



#~~~~~~~~~~~~~~~~~  КАРТОЧКА ТОВАРА  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



class GoodDetail(DetailView):
    model = Good
    template_name = "base_detail.html"

   

    @staticmethod
    def all_maincat():
        return Maincategory.objects.all()


    @staticmethod
    def all_category():
        return Category.objects.all()
























class GoodListView(ListView):
    model = Good
    template_name = "good_list.html"

class GoodDetailView(DetailView):
    model = Good
    template_name = "good_detail.html"

  
    @staticmethod
    def all_orders():
        return Order.objects.all()

    @staticmethod
    def all_peoples():
        return People.objects.all()





class CatListView(ListView):
    model = Category
    template_name = "cat_list.html"


    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_orders():
        return Order.objects.all()

    @staticmethod
    def all_peoples():
        return People.objects.all()





class CatDetailView(DetailView):
    model = Category
    template_name = "cat_detail.html"
    

    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_orders():
        return Order.objects.all()

    @staticmethod
    def all_peoples():
        return People.objects.all()




class OrderListView(ListView):
    model = Order
    template_name = "order_list.html"


    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_orders():
        return Order.objects.all()

    @staticmethod
    def all_peoples():
        return People.objects.all()





class OrderDetailView(DetailView):
    model = Order
    template_name = "order_detail.html"
    

    # @staticmethod
    # def all_goods():
    #     return Good.objects.all()

    @staticmethod
    def all_goods():
        return Good.objects.all()

    @staticmethod
    def all_orders():
        return Order.objects.all()

    @staticmethod
    def all_peoples():
        return People.objects.all()

    






# class CatsListView(ListView):
#     model = Category
#     template_name = "shop.html"

#     def get_context_data(self, **kwargs):
#         context = super(CatsListView, self).get_context_data(**kwargs)
#         context['goods'] = Good.objects.all()
#         return context


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



class CListView(ListView):
    model = Good
    template_name = "catalog/c_list.html"

class GDetailView(DetailView):
    model = Good
    template_name = "catalog/detail.html"


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class IndexView(ListView):
    model = Good
    template_name = "catalog/index.html"

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="">Home</a></li>
          <li><a href="">All goods</a></li>
          <li><a href="">All categorys</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>


   

catalog/templates/cat_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Категория: {{ order.name}} </h1>

  <!-- <p><strong>Description:</strong> <p>{{ good.decs}} {{ good.price}}</a></p> author detail link not yet defined
  <p><strong>Категория:</strong>{{good.category}}</p> -->
 


  <div style="margin-left:20px;margin-top:20px">
    <h4>Товары:</h4>

    ~~~~~~~~~~~
  
     {% for category in category.good_set.all %}
         <li>{{ category.name }}</a></li>
     {% endfor %}

    ~~~~~~~~~~~

     
    
  </div>
{% endblock %}

catalog/templates/cat_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Category List</h1>
 <div class="container">
   <div class="row">
     <div class="col">
       <h2>Category</h2>

        <h3>
          {% for cat in object_list %}
            <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
           {% endfor %}
          </h3>
        </div>
    

       <div class="col">
       	 <h2>Goods</h2>

          <h3>
           {% for item in view.all_goods %}
             <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
           {% endfor %}
          </h3>
        </div>

       
     
        <div class="col">
         <h2>Orders</h2>

          <h3>
           {% for item in view.all_orders %}
            <li><a href="{{ item.get_absolute_url }}">{{ item.name }}</a></li>
           {% endfor %}
          </h3>
         </div>


        <div class="col">  
        <h2>Users</h2>  

         <h3>
           {% for item in view.all_peoples %}
             <li>{{ item.name }}</li>
           {% endfor %}
         </h3>
        </div>   

        <div class="w-100"></div>

        <div class="col"> ~~~ 

         {% for category in category.good_set.all %}
         <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
         {% endfor %}


        </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
  
  </div>
</div>

{% endblock %}

catalog/templates/catalog/New folder/!testfile.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Category List</h1>
 <div class="container">
   <div class="row">
     <div class="col">
       <h2>Category</h2>

        <h3>
          {% for order in object_list %}
            <li><a href="{{ order.get_absolute_url }}">{{ order.name }}</a></li>
           {% endfor %}
          </h3>
        </div>
    

       <div class="col">
      <!--  	 <h2>Goods</h2>

          <h3>
           {% for item in view.all_goods %}
             <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
        </div>

       
     
        <div class="col">
         <h2>Orders</h2>

      <!--     <h3>
           {% for item in view.all_orders %}
            <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
         </div>


        <div class="col">  
        <h2>Users</h2>  

     <!--     <h3>
           {% for item in view.all_peoples %}
             <li>{{ item.name }}</li>
           {% endfor %}
         </h3> -->
        </div>   

        <div class="w-100"></div>

        <div class="col"> ~~~ 

         {% for category in category.good_set.all %}
         <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
         {% endfor %}


        </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
  
  </div>
</div>

{% endblock %}

catalog/templates/catalog/New folder/c_list.html
{% extends 'cat_base.html' %}


{% block content %}

{% for order in object_list %}
                   
<div class="col-sm-6 col-md-4">
			<div class="products">
				
	<div class="product">		
		<div class="product-image">
			<div class="image">
				<a href="detail.html"><img  src="assets/images/blank.gif" data-echo="assets/images/fashion-products/1.jpg" alt=""></a>
			</div><!-- /.image -->			

         

			<div class="tag new"><span>new</span></div>                        		   
		</div><!-- /.product-image -->
			
		
		<div class="product-info text-left">
			<h3 class="name"><a href="{{ order.get_absolute_url }}">{{ order.name }}</a></h3>

           

			<div class="rating rateit-small"></div>
			<div class="description"></div>

			<div class="product-price">	
				<span class="price">
					$650.99				</span>
										     <span class="price-before-discount">$ 800</span>
									
			</div><!-- /.product-price -->
			
		</div><!-- /.product-info -->
					<div class="cart clearfix animate-effect">
				<div class="action">
								
					<button class="btn btn-primary" type="button">Add to cart</button>
					<button class="left btn btn-primary" type="button"><i class="icon fa fa-heart"></i></button>
					<button class="left btn btn-primary" type="button"><i class="fa fa-retweet"></i></button>						

		                
					
				</div><!-- /.action -->
			</div><!-- /.cart -->
			</div><!-- /.product -->
      
			</div><!-- /.products -->
		</div><!-- /.item -->
	
{% endfor %}

{% endblock %}

catalog/templates/catalog/base_catalog.html
{% extends "base.html" %}


{% block content %}

{% for order in object_list %}
                   
<div class="col-sm-6 col-md-4">
			<div class="products">
				
	<div class="product">		
		<div class="product-image">
			<div class="image">
				<a href=""><img  src="{{ order.photo.url }}" data-echo="{{ order.photo.url }}" alt="" style="width:270px;height:270px;"></a>
			</div><!-- /.image -->			

         

			<div class="tag new"><span>new</span></div>                        		   
		</div><!-- /.product-image -->
			
		
		<div class="product-info text-left">
			<h3 class="name"><a href="">{{ order.name }}</a></h3>

           

			<div class="rating rateit-small"></div>
			<div class="description"></div>

			<div class="product-price">	
				<span class="price">
					$650.99				</span>
										     <span class="price-before-discount">$ 800</span>
									
			</div><!-- /.product-price -->
			
		</div><!-- /.product-info -->
					<div class="cart clearfix animate-effect">
				<div class="action">
								
					<button class="btn btn-primary" type="button">Add to cart</button>
					<button class="left btn btn-primary" type="button"><i class="icon fa fa-heart"></i></button>
					<button class="left btn btn-primary" type="button"><i class="fa fa-retweet"></i></button>						

		                
					
				</div><!-- /.action -->
			</div><!-- /.cart -->
			</div><!-- /.product -->
      
			</div><!-- /.products -->
		</div><!-- /.item -->
	
{% endfor %}

{% endblock %}

catalog/templates/catalog/base_catalog_detail.html
{% extends "base.html" %}


     


{% block content %}


{% for good in category.good_set.all %}
  
                   
<div class="col-sm-6 col-md-4">
			<div class="products">
				
	<div class="product">		
		<div class="product-image">
			<div class="image">
				<a href="{{ good.get_absolute_url }}"><img  src="{{ good.photo.url }}" data-echo="{{ good.photo.url }}" alt="" style="width:270px;height:270px;"></a>
			</div><!-- /.image -->			

         

			<div class="tag new"><span>new</span></div>                        		   
		</div><!-- /.product-image -->
			
		
		<div class="product-info text-left">
			<h3 class="name"><a href="{{ order.get_absolute_url }}">{{ good.name }}</a></h3>

           

			<div class="rating rateit-small"></div>
			<div class="description"></div>

			<div class="product-price">	
				<span class="price">
					$650.99				</span>
										     <span class="price-before-discount">$ 800</span>
									
			</div><!-- /.product-price -->
			
		</div><!-- /.product-info -->
					<div class="cart clearfix animate-effect">
				<div class="action">
								
					<button class="btn btn-primary" type="button">Add to cart</button>
					<button class="left btn btn-primary" type="button"><i class="icon fa fa-heart"></i></button>
					<button class="left btn btn-primary" type="button"><i class="fa fa-retweet"></i></button>						

		                
					
				</div><!-- /.action -->
			</div><!-- /.cart -->
			</div><!-- /.product -->
      
			</div><!-- /.products -->
		</div><!-- /.item -->
	
  {% endfor %}




{% endblock %}

catalog/templates/catalog/base_main_catalog_detail.html
{% extends "base.html" %}


     


{% block content %}


{% for good in view.all_goods %}
  
                   
<div class="col-sm-6 col-md-4">
			<div class="products">
				
	<div class="product">		
		<div class="product-image">
			<div class="image">
				<a href="{{ good.get_absolute_url }}"><img  src="{{ good.photo.url }}" data-echo="{{ good.photo.url }}" alt="" style="width:270px;height:270px;"></a>
			</div><!-- /.image -->			

         

			<div class="tag new"><span>new</span></div>                        		   
		</div><!-- /.product-image -->
			
		
		<div class="product-info text-left">
			<h3 class="name"><a href="{{ order.get_absolute_url }}">{{ good.name }}</a></h3>

           

			<div class="rating rateit-small"></div>
			<div class="description"></div>

			<div class="product-price">	
				<span class="price">
					$650.99				</span>
										     <span class="price-before-discount">$ 800</span>
									
			</div><!-- /.product-price -->
			
		</div><!-- /.product-info -->
					<div class="cart clearfix animate-effect">
				<div class="action">
								
					<button class="btn btn-primary" type="button">Add to cart</button>
					<button class="left btn btn-primary" type="button"><i class="icon fa fa-heart"></i></button>
					<button class="left btn btn-primary" type="button"><i class="fa fa-retweet"></i></button>						

		                
					
				</div><!-- /.action -->
			</div><!-- /.cart -->
			</div><!-- /.product -->
      
			</div><!-- /.products -->
		</div><!-- /.item -->
	
  {% endfor %}




{% endblock %}

catalog/templates/good_detail.html
{% extends "base_generic.html" %}

{% block content %}



  <h1>Товар: {{ good.name}} </h1>  
  <h1>Пользователь: {{ good.people }} </h1>



    ~~~~~~~~~~~


  {% for order in good.order_set.all %}
         <h3><li>{{ order.name }}</li></h3>
  {% endfor %}

    ~~~~~~~~~~~


  {% for good in good.order_set.all %}
         <h3><li>{{ good.people }}</li></h3>
  {% endfor %}

    ~~~~~~~~~~~

  </div>
{% endblock %}

catalog/templates/good_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Category List</h1>
 <div class="container">
   <div class="row">
     <div class="col">
       <h2>Category</h2>

        <h3>
          {% for order in object_list %}
            <li><a href="{{ order.get_absolute_url }}">{{ order.name }}</a></li>
           {% endfor %}
          </h3>
        </div>
    

       <div class="col">
      <!--  	 <h2>Goods</h2>

          <h3>
           {% for item in view.all_goods %}
             <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
        </div>

       
     
        <div class="col">
         <h2>Orders</h2>

      <!--     <h3>
           {% for item in view.all_orders %}
            <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
         </div>


        <div class="col">  
        <h2>Users</h2>  

     <!--     <h3>
           {% for item in view.all_peoples %}
             <li>{{ item.name }}</li>
           {% endfor %}
         </h3> -->
        </div>   

        <div class="w-100"></div>

        <div class="col"> ~~~ 

         {% for category in category.good_set.all %}
         <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
         {% endfor %}


        </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
  
  </div>
</div>

{% endblock %}

catalog/templates/order_detail.html
{% extends "base_generic.html" %}

{% block content %}



  <h1>Заказ: {{ order.name}} </h1>  
  <h1>Пользователь: {{ order.people}} </h1>



    ~~~~~~~~~~~


   {% for order in order.good.all %} 
    <h3>Товар: {{ order.name }} </h3>
  {% endfor %}
  

    ~~~~~~~~~~~



  </div>
{% endblock %}

catalog/templates/order_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Category List</h1>
 <div class="container">
   <div class="row">
     <div class="col">
       <h2>Category</h2>

        <h3>
          {% for order in object_list %}
            <li><a href="{{ order.get_absolute_url }}">{{ order.name }}</a></li>
           {% endfor %}
          </h3>
        </div>
    

       <div class="col">
      <!--  	 <h2>Goods</h2>

          <h3>
           {% for item in view.all_goods %}
             <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
        </div>

       
     
        <div class="col">
         <h2>Orders</h2>

      <!--     <h3>
           {% for item in view.all_orders %}
            <li>{{ item.name }}</li>
           {% endfor %}
          </h3> -->
         </div>


        <div class="col">  
        <h2>Users</h2>  

     <!--     <h3>
           {% for item in view.all_peoples %}
             <li>{{ item.name }}</li>
           {% endfor %}
         </h3> -->
        </div>   

        <div class="w-100"></div>

        <div class="col"> ~~~ 

         {% for category in category.good_set.all %}
         <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
         {% endfor %}


        </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
        <div class="col"> ~~~ </div> 
  
  </div>
</div>

{% endblock %}